version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.13.4
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-34-194-123-31.compute-1.amazonaws.com
            port: '5432'
            database: d7up7ciq8147aq
            ssl: true
            user: jmcpvomxvqtmzv
            password: c0194dc458ef49136d690e27dbe49064b7ccd8d5d118571d8881aca56950e88e
            migrations: true